version: '3.8'

services:
  guest_service:
    build: ./services/guest_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/guest_db
    volumes:
      - ./services/guest_service/src:/app/src
    depends_on:
      - postgres

  room_service:
    build: ./services/room_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/room_db
    volumes:
      - ./services/room_service/src:/app/src
    depends_on:
      - postgres

  booking_service:
    build: ./services/booking_service
    ports:
      - "8003:8003"
    environment:
      - GUEST_SERVICE_URL=http://guest_service:8001
      - ROOM_SERVICE_URL=http://room_service:8002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/booking_db
    volumes:
      - ./services/booking_service/src:/app/src
    depends_on:
      - guest_service
      - room_service
      - postgres

  postgres:
    image: postgres:15
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
